export { HomePage } from './Home';
export { HowItWorksPage } from './HowItWorks';
export { PrivacyPage } from './Privacy';
export { PrivacyPolicyPage } from './PrivacyPolicy';
export { PricingPage } from './Pricing';
export { FAQPage } from './FAQ';
export { SampleImpactPage } from './SampleImpactPage';
export { PortfolioPage } from './Portfolio';
export { TermsOfServicePage } from './TermsOfService';
