/**
 * Field-level content changes for the Sanity `contentPage` documents.
 *
 * Every change is an exact text swap: `before` must occur exactly once in the
 * field's current value, and is replaced by `after`. Nothing else in the
 * document is touched, so edits made in the Studio since the change list was
 * written survive, and a change whose text has moved on is reported instead
 * of guessed at. New documents are created only if their id doesn't exist.
 *
 * Change lists: scripts/sanity-content/changes/*.json
 * New documents: scripts/sanity-content/new/*.json
 *
 * Usage:
 *   npm run content:patch             dry run: checks every change against the live dataset
 *   npm run content:patch -- --apply  writes (needs SANITY_API_WRITE_TOKEN in .env.local)
 *   npm run content:patch -- --docs   rewrites docs/sanity-content-changes.md from the lists
 *
 * Each document is patched in one transaction guarded by its revision id, so
 * a concurrent Studio edit makes that document fail cleanly; run it again.
 */

import fs from 'fs';
import path from 'path';
import { createClient } from '@sanity/client';
import { applyChanges, loadChanges, loadNewDocs, type DocChanges, type NewContentDoc, type Outcome } from '../src/lib/sanity/contentChanges';

const ROOT = process.cwd();
const DOC_OUT = path.join(ROOT, 'docs/sanity-content-changes.md');

function writeDoc(docs: DocChanges[], created: NewContentDoc[]) {
  const fence = (s: string) => {
    const ticks = s.includes('```') ? '````' : '```';
    return `${ticks}text\n${s}\n${ticks}`;
  };
  const lines = [
    '# Sanity content changes',
    '',
    'Generated by `npm run content:patch -- --docs` from `scripts/sanity-content/`. Do not edit by hand.',
    '',
    'Every change is an exact swap in one field of one `contentPage` document. Apply them with',
    '`npm run content:patch -- --apply` (dry run first without `--apply`), or by hand in the Studio.',
    '',
  ];
  for (const doc of created) {
    lines.push(`## New document: ${doc._id}`, '', `Section \`${doc.section}\`, slug \`${doc.slug.current}\`.`, '');
    for (const field of ['title', 'description', 'headline', 'order', 'body']) {
      const value = (doc as unknown as Record<string, unknown>)[field];
      if (value !== undefined) lines.push(`**${field}**`, '', fence(String(value)), '');
    }
  }
  for (const doc of docs) {
    lines.push(`## ${doc.docId}`, '', `${doc.changes.length} changes.`, '');
    doc.changes.forEach((c, i) => {
      lines.push(`### ${i + 1}. ${c.field} (${c.why})`, '', 'Before:', '', fence(String(c.before)), '', 'After:', '', fence(String(c.after)), '');
    });
  }
  fs.writeFileSync(DOC_OUT, lines.join('\n'));
  console.log(`Wrote ${path.relative(ROOT, DOC_OUT)}`);
}

async function main() {
  const args = new Set(process.argv.slice(2));
  const docs = loadChanges();
  const created = loadNewDocs();
  if (args.has('--docs')) return writeDoc(docs, created);

  const apply = args.has('--apply');
  const projectId = process.env.NEXT_PUBLIC_SANITY_PROJECT_ID;
  const dataset = process.env.NEXT_PUBLIC_SANITY_DATASET ?? 'production';
  const token = process.env.SANITY_API_WRITE_TOKEN;
  if (!projectId) throw new Error('Missing NEXT_PUBLIC_SANITY_PROJECT_ID.');
  if (apply && !token) throw new Error('--apply needs SANITY_API_WRITE_TOKEN (Editor) in the environment.');
  const client = createClient({ projectId, dataset, apiVersion: '2025-01-01', token, useCdn: false });

  let problems = 0;
  for (const doc of docs) {
    const current = await client.getDocument(doc.docId);
    if (!current) {
      console.log(`✗ ${doc.docId}: document not found`);
      problems++;
      continue;
    }
    const { next, outcomes } = applyChanges(current, doc.changes);
    const tally = (o: Outcome) => outcomes.filter((x) => x === o).length;
    console.log(`${doc.docId}: ${tally('ok')} to apply, ${tally('applied-already')} already applied, ${tally('missing') + tally('ambiguous')} problems`);
    const docProblems = tally('missing') + tally('ambiguous');
    outcomes.forEach((o, i) => {
      if (o === 'missing' || o === 'ambiguous') {
        problems++;
        const c = doc.changes[i];
        console.log(`  ✗ #${i + 1} ${c.field}: ${o === 'missing' ? 'text not found' : 'text found more than once'}: ${JSON.stringify(String(c.before).slice(0, 90))}`);
      }
    });
    if (apply && docProblems) console.log('  skipped: fix the problems above first, nothing written for this document');
    else if (apply && Object.keys(next).length) {
      await client.patch(doc.docId).ifRevisionId(current._rev).set(next).commit();
      console.log('  written');
    }
  }
  for (const doc of created) {
    const exists = await client.getDocument(doc._id);
    console.log(`${doc._id}: ${exists ? 'exists, left as is' : 'new'}`);
    if (apply && !exists) {
      await client.createIfNotExists({ ...doc });
      console.log('  created');
    }
  }
  if (!apply) console.log(problems ? `\nDry run: ${problems} problems. Nothing written.` : '\nDry run: every change applies cleanly. Nothing written; add --apply to write.');
  if (problems) process.exitCode = 1;
}

if (process.argv[1] && path.resolve(process.argv[1]) === path.resolve(__filename)) {
  main().catch((error) => {
    console.error(error instanceof Error ? error.message : error);
    process.exit(1);
  });
}
